### ISSUE TITLE
[BUG] Submitting Data TX (JSON) through client broken

### ISSUE THREAD

**Issue by greywolf42069** [TurtleNetwork/TurtleNetworkGUI#32]
![image](https://user-images.githubusercontent.com/55455281/75385516-7f7d7d00-58a5-11ea-906b-f2fcea957b5f.png)
after hitting continue it shows this and sits forever

**Comment by xucito** [comment]
This has to do with incorrect fees for transaction type 13.

Fee was previously 1000000 but requires 100000000 TN.

Updated in the [fee.json](https://github.com/TurtleNetwork/waves-client-config/blob/master/fee.json) and should be working now.

**Comment by xucito** [comment]
This issue is actually in the way you are submitting null scripts.

The field should not take "null" but rather the full TX in json form.

Have added a null check to say syntax error if you insert just null (This was previously not throwing an error)

![image](https://user-images.githubusercontent.com/36687889/75614059-fdfc4800-5b4d-11ea-9bfa-d686fb5d33d8.png)


Example below:
```json
{
    "type": 13,
    "version": 1,
    "senderPublicKey": "CJRtRe9c5jbZBqaLJcsuNRjvBTqG8vqUqej4ybegjPdh",
    "chainId": 108,
    "fee": 104000000,
    "timestamp": 1583005690435,
    "proofs": [
        "4qi1PFrpmrhpsf9yw4Q5NVogqCVe45LJfFs5CVeJgkqFQmFS6tNgNEfYYsfySvSsUzr5WajUvxxXYY6D5WknNp4E"
    ],
    "id": "3Toyt8dc1Qrf751chNUqfs4TbU45j1kqR1SAq9GEsCeH",
    "script": null
}
```
